################################################################
#
# Pipeline pipeline_single_cell.py configuration file
#
# This pipeline.yml file lists some configuration options that you
# need to set before running the pipeline.
#
################################################################

# genome ID
genome: hg38
genome_dir: /ifs/mirror/genomes/index/

# Location of the single cell directory
sc_dir: '/Users/annajames-bott/Documents/Dphil/Repositories/single-cell'

# Project name
projectname: proj025

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2019)

# Pseduoaligner
# allowble quantifiers:
# alevin
# kallisto
# bustools??
quantifiers: [kallisto, bustools]


# Provide a reference geneset (suffix= ".gtf.gz")
# Geneset should be located in working directory
geneset: refgeneset.gtf.gz


####################
# kallisto options
####################

kallisto:
  # kmer size for kallisto. Default is 31 and max is 31
  # Used to generate the kallisto indexed
  # Kallisto will ignore transcripts shorter than This
  kmer: 31

  # number of threads for kallisto
  threads: 1

  # Whether to generate a BUStools file
  bustools: 1
  # Must specify single cell technology to generate bustools file
  # Allowable sc technology:
  # 10Xv1
  # 10Xv2
  # DropSeq
  # inDrop
  # CELSeq
  # CELSeq2
  # SCRBSeq
  # Note that 10Xv3 is not supported in version 0.44 of Kallisto
  sctechnology: 10Xv2


salmon:

  # Number of threads that can be used by alevin to perfrom the quantification
  threads: 10

  # Library type must be specified.
  # ISR recommended for DropSeq and 10xV2 technology
  librarytype: ISR

  # Single cell technology/protocol to be specified
  # Allowable sc technology:
  # dropseq
  # chromium
  sctechnology: dropseq
