##########################
#
# configuration file for pipeline_singlecell
#
##########################

# primary assembly downloaded according to documentation instructions
genome_file: Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

# Provide a reference geneset (suffix= ".gtf.gz")
# Geneset should be located in working directory
geneset: Homo_sapiens.GRCh38.99.gtf.gz

# This is the location of the intron.bed.gz
intron_bed: introns.bed.gz

# This is the location of the cDNA fasta
cdna_fasta: cDNA.fa.gz

# Specify if there is a mixed species input (i.e. mouse and human)
mixed_species: 0

# If there is a mixed specied input specify the extra genome (in addition to the
# one already specified)
genome2:
genome_dir2: /ifs/mirror/genomes/index/

# If there is a mixed specied input specify a reference geneset (suffix= ".gtf.gz")
# Geneset should be located in working directory
geneset2:

# Location of the single cell directory
sc_dir: '/ifs/projects/adam/single-cell-test/'

# Project name
projectname: test

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2019)

# Location of the data. 0 for the current directory
data: 0



#######################
# Kallisto options
#######################

kallisto:
  # kmer size for kallisto. Default is 31 and max is 31
  # Used to generate the kallisto index
  # Kallisto will ignore transcripts shorter than this
  kmer: 31

  # Number of threads for kallisto
  threads: 5

  # Whether to generate a BUStools file
  bustools: 0
  # Must specify a single cell tchnology to generate bustools file
  # allowable technology:
  # 10Xv1
  # 10Xv2
  # DropSeq
  # inDrop
  # CELSeq
  # CELSeq2
  # SCRBSeq
  # Not that 10Xv3 is not supported in version 0.44 of kallisto
  sctechnology: DropSeq

  # whether to output as loom or h5
  # Must specify:
  # loom
  # h5ad
  output_format: h5ad

  # Which workflow to use:
  # options include: standard,lamanno,nucleus,kite,kite:10xFB
  # Type of workflow. Use `lamanno` for RNA velocity based
  #                      on La Manno et al. 2018 logic. Use `nucleus` for RNA
  #                      velocity on single-nucleus RNA-seq reads. Use `kite`
  #                      for feature barcoding. Use `kite:10xFB` for 10x
  #                      Genomics Feature Barcoding technology. (default:
  #                      standard)
  workflow: standard

  # Expected number of cells
  num_cells: 3000

###########################################
# Running Jupyter notebook Scanpy filtering
###########################################

# Once you have ran the pipelpeline to full task then
# the next step is to perform filtering on all of your data.
# I would suggest that you first run this with default settings
# Look at the output and then delete the output files, modify the
# settings below then re-run the pipeline.

filtering:

  # Set the minimum nuber of counts for each cell
  min_counts: 50

  # Set the maximum counts for each cell
  max_counts: 5000

  # Set the maximum percentage of mitochrondria to threshold below
  percent_mito: 0.2

  # Set the minimum number of genes for each cell
  min_genes: 50

  # Filter genes that express greater than ? genes - filter out 0 counts
  zero_genes: 10
