##########################
#
# configuration file for pipeline_singlecell
#
##########################

# Download primary transcripts e.g.:
# ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.transcripts.fa.gz
prim_trans1: gencode.v34.transcripts.fa.gz

# Download genome e.g.:
# ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/GRCh38.primary_assembly.genome.fa.gz
genome1: GRCh38.primary_assembly.genome.fa.gz


# Specify if there is a mixed species input (i.e. mouse and human)
mixed_species: 0

# Download primary transcripts e.g.:
# ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.transcripts.fa.gz
prim_trans2: gencode.v34.transcripts.fa.gz

# Download genome e.g.:
# ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/GRCh38.primary_assembly.genome.fa.gz
genome2: GRCh38.primary_assembly.genome.fa.gz



# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2020)

# Location of the data. 0 for the current directory
data: 0

#######################
# Kallisto
#######################

kallisto:
  # kmer size for kallisto. Default is 31 and max is 31
  # Used to generate the kallisto index
  # Kallisto will ignore transcripts shorter than this
  kmer: 31

  # Number of threads for kallisto
  threads: 5

  # Whether to generate a BUStools file
  bustools: 0
  # Must specify a single cell tchnology to generate bustools file
  # allowable technology:
  # 10Xv1
  # 10Xv2
  # DropSeq
  # inDrop
  # CELSeq
  # CELSeq2
  # SCRBSeq
  # Not that 10Xv3 is not supported in version 0.44 of kallisto
  sctechnology: DropSeq

  expectedcells: 1500

salmon:

  # Length of kmer for indexing
  kmer: 31

  job_memory: 30G

  # Number of threads that can be used by alevin to perform the quantification
  threads: 10

  # Library type
  # ISR recommended for DropSeq and 10Xv2 technology
  librarytype: ISR

  # Optional options
  # See https://salmon.readthedocs.io/en/latest/salmon.html#description-of-important-options
  # for a list of more salmon options
  index_options: ''

  run_options: ''

  # Wether to run alevin
  alevin: 1

  # Single cell technology/protocol to be specified
  # Allowable sc technology:
  # dropseq
  # chromium
    # for 10x chromium v2 sc protocol
  # chromiumV3
  # gemcode
    # for 10x gemocode v1 sc protocol
  # celseq
  # celseq2
  sctechnology: dropseq

fastp:

  options: ''
