##########################
#
# configuration file for pipeline_singlecell
#
##########################

# genomeID
genome: hg38
genome_dir: /ifs/mirror/genomes/index/

# Provide a reference geneset (suffix= ".gtf.gz")
# Geneset should be located in working directory
geneset: human_geneset_all.gtf.gz

# Specify if there is a mixed species input (i.e. mouse and human)
mixed_species: 0

# If there is a mixed specied input specify the extra genome (in addition to the
# one already specified)
genome2: 
genome_dir2: /ifs/mirror/genomes/index/

# If there is a mixed specied input specify a reference geneset (suffix= ".gtf.gz")
# Geneset should be located in working directory
geneset2:

# Location of the single cell directory
sc_dir: '/ifs/projects/adam/single-cell-test/'

# Project name
projectname: test

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2019)

# Location of the data. 0 for the current directory
data: 0

#######################
# Kallisto
#######################

kallisto:
  # kmer size for kallisto. Default is 31 and max is 31
  # Used to generate the kallisto index
  # Kallisto will ignore transcripts shorter than this
  kmer: 31

  # Number of threads for kallisto
  threads: 5

  # Whether to generate a BUStools file
  bustools: 0
  # Must specify a single cell tchnology to generate bustools file
  # allowable technology:
  # 10Xv1
  # 10Xv2
  # DropSeq
  # inDrop
  # CELSeq
  # CELSeq2
  # SCRBSeq
  # Not that 10Xv3 is not supported in version 0.44 of kallisto
  sctechnology: DropSeq

  expectedcells: 1500

salmon:

  # Length of kmer for indexing
  kmer: 31

  job_memory: 30G

  # Number of threads that can be used by alevin to perform the quantification
  threads: 10

  # Library type
  # ISR recommended for DropSeq and 10Xv2 technology
  librarytype: ISR

  # Optional options
  # See https://salmon.readthedocs.io/en/latest/salmon.html#description-of-important-options
  # for a list of more salmon options
  index_options: ''

  run_options: ''

  # Wether to run alevin
  alevin: 1

  # Single cell technology/protocol to be specified
  # Allowable sc technology:
  # dropseq
  # chromium
    # for 10x chromium v2 sc protocol
  # chromiumV3
  # gemcode
    # for 10x gemocode v1 sc protocol
  # celseq
  # celseq2
  sctechnology: dropseq

fastp:

  options: ''
